Implement event listener to revalidate static content on node.updated…
enonic/lib-nextjs-proxy pull request #76
Opened 2022-07-20 08:54 UTC by pmi

… event #75

2022-08-04 10:20 UTC, poi33 requested changes

2022-08-04 10:20 UTC, poi33 commented on src/main/resources/lib/nextjs-proxy/event.es6
> +        _name: 'hmdb'
Hardcoded site in the proxy?

2022-08-08 13:42 UTC, pmi commented on src/main/resources/lib/nextjs-proxy/event.es6
> +        _name: 'hmdb'
this needs to be dynamic of course

2022-08-09 08:36 UTC, poi33 approved these changes

2022-08-10 14:17 UTC, merged